CREATE TABLE USER
(
    ID           INT AUTO_INCREMENT,
    ACCOUNT_ID   VARCHAR(100),
    NAME         VARCHAR(50),
    TOKEN        CHAR(36),
    GMT_CREATE    BIGINT,
    GMT_MODIFIED BIGINT,
    bio VARCHAR(256),
    CONSTRAINT USER_PK
        PRIMARY KEY (ID)
);